version: '2'
services:
  vue:
    build:
      context: .
      dockerfile: docker/VueDockerfile
    working_dir: /var/app
    environment:
      APP_HOST: localhost:3000
      TZ: Asia/Tokyo
    command: /bin/sh -c 'yarn install&& yarn run start'
    volumes:
      - .:/var/app
    ports:
      - 3000:3000

volumes:
  bundle:
